spring.profiles.active=h2,local,redis-prod
spring.data.rest.base-path=/zmart/product
info.build.name=PerishableProductsService
logging.level.org.springframework.web=INFO
# /info
info.app.name=Perishable Products Service
info.app.description=Perishable Products Service tracks inventory by quality and number sold using SpringBoot
info.app.version=1.0.0