# This is a placeholder PROD profile.
# Remove below line when real prod port provided
server.port=8181
# endPoint=
# appId=
# lifecycleEndPoint=
# Actuator
management.endpoints.web.exposure.exclude=*
management.endpoints.jmx.exposure.include=health
# /health
endpoints.beans.id=springbeans
endpoints.beans.enabled=true
endpoints.beans.sensitive=false
