server.port=8181
# Toggle embedded redis server
local.redis.server.embedded=ON
# Actuator
management.endpoints.web.exposure.include=info,health
management.endpoints.jmx.exposure.include=info,health
# /health
management.endpoint.health.enabled=true
endpoints.beans.id=springbeans
endpoints.beans.enabled=true
endpoints.beans.sensitive=false


